const order = {
  type: 'order',
  delivery: {
    _isAMomentObject: true,
    _isUTC: false,
    _pf: {
      empty: false,
      unusedTokens: [],
      unusedInput: [],
      overflow: -2,
      charsLeftOver: 0,
      nullInput: false,
      invalidEra: null,
      invalidMonth: null,
      invalidFormat: false,
      userInvalidated: false,
      iso: false,
      parsedDateParts: [],
      era: null,
      meridiem: null,
      rfc2822: false,
      weekdayMismatch: false,
    },
    _locale: {
      _calendar: {
        sameDay: '[Idag] LT',
        nextDay: '[Imorgon] LT',
        nextWeek: '[På] dddd LT',
        lastDay: '[Igår] LT',
        lastWeek: '[I] dddd[s] LT',
        sameElse: 'L',
      },
      _longDateFormat: {
        LTS: 'HH:mm:ss',
        LT: 'HH:mm',
        L: 'YYYY-MM-DD',
        LL: 'D MMMM YYYY',
        LLL: 'D MMMM YYYY [kl.] HH:mm',
        LLLL: 'dddd D MMMM YYYY [kl.] HH:mm',
        lll: 'D MMM YYYY HH:mm',
        llll: 'ddd D MMM YYYY HH:mm',
      },
      _invalidDate: 'Invalid date',
      _dayOfMonthOrdinalParse: {},
      _relativeTime: {
        future: 'om %s',
        past: 'för %s sedan',
        s: 'några sekunder',
        ss: '%d sekunder',
        m: 'en minut',
        mm: '%d minuter',
        h: 'en timme',
        hh: '%d timmar',
        d: 'en dag',
        dd: '%d dagar',
        w: 'a week',
        ww: '%d weeks',
        M: 'en månad',
        MM: '%d månader',
        y: 'ett år',
        yy: '%d år',
      },
      _months: [
        'januari',
        'februari',
        'mars',
        'april',
        'maj',
        'juni',
        'juli',
        'augusti',
        'september',
        'oktober',
        'november',
        'december',
      ],
      _monthsShort: [
        'jan',
        'feb',
        'mar',
        'apr',
        'maj',
        'jun',
        'jul',
        'aug',
        'sep',
        'okt',
        'nov',
        'dec',
      ],
      _week: { dow: 1, doy: 4 },
      _weekdays: [
        'söndag',
        'måndag',
        'tisdag',
        'onsdag',
        'torsdag',
        'fredag',
        'lördag',
      ],
      _weekdaysMin: ['sö', 'må', 'ti', 'on', 'to', 'fr', 'lö'],
      _weekdaysShort: ['sön', 'mån', 'tis', 'ons', 'tor', 'fre', 'lör'],
      _meridiemParse: {},
      _abbr: 'sv',
      _config: {
        calendar: {
          sameDay: '[Idag] LT',
          nextDay: '[Imorgon] LT',
          nextWeek: '[På] dddd LT',
          lastDay: '[Igår] LT',
          lastWeek: '[I] dddd[s] LT',
          sameElse: 'L',
        },
        longDateFormat: {
          LTS: 'HH:mm:ss',
          LT: 'HH:mm',
          L: 'YYYY-MM-DD',
          LL: 'D MMMM YYYY',
          LLL: 'D MMMM YYYY [kl.] HH:mm',
          LLLL: 'dddd D MMMM YYYY [kl.] HH:mm',
          lll: 'D MMM YYYY HH:mm',
          llll: 'ddd D MMM YYYY HH:mm',
        },
        invalidDate: 'Invalid date',
        dayOfMonthOrdinalParse: {},
        relativeTime: {
          future: 'om %s',
          past: 'för %s sedan',
          s: 'några sekunder',
          ss: '%d sekunder',
          m: 'en minut',
          mm: '%d minuter',
          h: 'en timme',
          hh: '%d timmar',
          d: 'en dag',
          dd: '%d dagar',
          w: 'a week',
          ww: '%d weeks',
          M: 'en månad',
          MM: '%d månader',
          y: 'ett år',
          yy: '%d år',
        },
        months: [
          'januari',
          'februari',
          'mars',
          'april',
          'maj',
          'juni',
          'juli',
          'augusti',
          'september',
          'oktober',
          'november',
          'december',
        ],
        monthsShort: [
          'jan',
          'feb',
          'mar',
          'apr',
          'maj',
          'jun',
          'jul',
          'aug',
          'sep',
          'okt',
          'nov',
          'dec',
        ],
        week: { dow: 1, doy: 4 },
        weekdays: [
          'söndag',
          'måndag',
          'tisdag',
          'onsdag',
          'torsdag',
          'fredag',
          'lördag',
        ],
        weekdaysMin: ['sö', 'må', 'ti', 'on', 'to', 'fr', 'lö'],
        weekdaysShort: ['sön', 'mån', 'tis', 'ons', 'tor', 'fre', 'lör'],
        meridiemParse: {},
        abbr: 'sv',
      },
      _dayOfMonthOrdinalParseLenient: {},
    },
    _d: { $$date: 1713186399098 },
    _isValid: true,
  },
  price: 123.30000000000001,
  customer: 'abc123' | null,
  _id: 'xpoLZjEATRNE0D8u',
}

const menu = {
  type: 'menu',
  id: 1,
  title: 'Bryggkaffe',
  desc: 'Bryggd på månadens bönor.',
  price: 39,
  applicablePromotion: true,
  discountedPrice: 30,
  _id: 'xpoLZjEDFTRN0D5u',
}

const user = {
  type: 'user',
  password: 'hemligtHashLosen',
  username: 'mattias',
  _id: 'abc123',
}
